# Generated by Django 5.2.7 on 2025-11-05 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=201)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=102)),
                ('specialization', models.CharField(max_length=301)),
                ('joined_date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
